[os]
disabled = false

[username]
style_user = "green bold"
style_root = "red bold"
# format = "[$user]($style) 🌚 "
format = "[$user]($style)[@](purple bold)"
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = '🌐 '
format = '[$hostname](bold yellow) '
disabled = false

[directory]
read_only = " 󰌾"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "...\\"
style = "bold italic blue"
home_symbol = "C:\\Users\\marek"

[shell]
disabled = false
format = '[$indicator]($style)' # removed space from default
unknown_indicator = 'unknown shell'
powershell_indicator = 'psh'
pwsh_indicator = 'pwsh'

# Replace the "❯" symbol in the prompt with "➜"
# Replace the "✗" symbol in the prompt with ""
[character]
# format = '$symbol' # removed space from default
success_symbol = "[❯](bold cyan)"
error_symbol = "[✗](bold red)"

[memory_usage]
symbol = '🐏 '
threshold = 85 # default: 75
format = '$symbol[${ram_pct}|${swap_pct}]($style) '
disabled = false

[cmd_duration]
# min_time = 1 # in [ms], default: 2_000
# show_milliseconds = true
disabled = false
style = "bold italic red"

[sudo]
symbol = '🧙 '
style = 'bold blue'
disabled = false

# [time]
# disabled = false

[c]
disabled = false

[java]
symbol = '☕ '
disabled = false

[python]
symbol = '🐍 '
disabled = false

[cmake]
symbol = '🛠️ '
disabled = false

# ----------

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[cpp]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
